### ISSUE TITLE
JIT trace

### ISSUE THREAD

**Issue by anasvaf** [alokprasad/fastspeech_squeezewave#3]
Hello. Did the following lines of code in synthesis.py work for you?

```
# script for generating torch script
traced_script_module = torch.jit.trace(model, (sequence, src_pos))
traced_script_module.save("traced_fastspeech_model.pt")
```

I get the following error:

>  RuntimeError: 0 INTERNAL ASSERT FAILED at ..\torch\csrc\jit\ir\alias_analysis.cpp:318, please report a bug to PyTorch. We don't have an op for aten::to but it isn't a special case.  Argument types: Tensor, None, int, Device, bool, bool, bool, int,

**Comment by alokprasad** [comment]
nope ..probably torch script are too frustrating ...see https://github.com/dathudeptrai/TensorflowTTS for Tensorflow implementation of fastspeech

**Comment by anasvaf** [comment]
@alokprasad Thank you for the prompt response!
